### PR TITLE
Added FileB in VersionB Branch

### PR DESCRIPTION
**Pull request by vj1089**

### CODE REVIEW

**Review by vj1089 — COMMENTED** [review]
Unable to seed Line to in the file. Please re-add line and re-submit pull request.

**Review by vjazdemo02 — CHANGES_REQUESTED** [review]
Rejected for changes to add new line

**Review by vjazdemo02 — CHANGES_REQUESTED** [review]
No changes seen. Rejected

**Review by vj1089 — COMMENTED** [review]
I have update FileB by adding new line and added FileD as per the request

**Review by vjazdemo02 — APPROVED** [review]

**Pull request merged**
